# Generated by Django 4.2.23 on 2026-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="final_cta_headline",
            field=models.CharField(
                blank=True, default="Ready to Work Together?", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="final_cta_label",
            field=models.CharField(blank=True, default="Get in Touch", max_length=80),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="final_cta_subtext",
            field=models.TextField(
                blank=True,
                default="Let's discuss how we can help you build innovative solutions for your organization.",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="final_cta_url",
            field=models.CharField(blank=True, default="/contact/", max_length=255),
        ),
    ]
