# Generated by Django 4.2.23 on 2026-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Show on homepage as featured"
            ),
        ),
    ]
