# Generated by Django 4.2 on 2026-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_casestudy_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceinquiry",
            name="estimated_budget",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="serviceinquiry",
            name="preferred_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
