# Generated by Django 4.2.23 on 2026-03-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_serviceinquiry_estimated_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Brief description of the category",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
    ]
